runtime: python39  # Menggunakan runtime standar untuk hosting HTML statis
service: fe-may-t7  # Nama layanan App Engine, bisa diubah sesuai kebutuhan
instance_class: F1  # Kelas instance untuk App Engine (F1 adalah kelas standar yang ringan)

handlers:
  - url: /pages
    static_dir: pages

  - url: /style
    static_dir: style

  - url: /javascript
    static_dir: javascript

  - url: /assets
    static_dir: assets

  - url: /
    static_files: pages/home.html
    upload: pages/home.html

default_expiration: "1h"  # Waktu cache default
