runtime: python39
service: fe-may-t7
instance_class: F1

handlers:
  - url: /pages
    static_dir: pages

  - url: /style
    static_dir: style

  - url: /javascript
    static_dir: javascript

  - url: /assets
    static_dir: assets

  - url: /
    static_files: pages/home.html
    upload: pages/home.html

# default_expiration opsional, boleh ditambah
default_expiration: "1h"
