runtime: python39  # Menggunakan runtime standar untuk hosting HTML statis
service: fe-may-t7  # Nama layanan App Engine, bisa diubah sesuai kebutuhan
instance_class: F1  # Kelas instance untuk App Engine (F1 adalah kelas standar yang ringan)

handlers:
  - url: /
    static_files: frontend/pages/home.html
    upload: frontend/pages/home.html

  - url: /(.*)
    static_files: frontend/\1
    upload: frontend/(.*)

default_expiration: "1h"  # Waktu cache default
