GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoidGVzQGdtYWlsLmNvbSIsImlhdCI6MTc0Nzg0NDczNSwiZXhwIjoxNzQ3ODQ0NzQ1fQ.bEeE9h15DW_Cu7PHiPSC34eM3FyiAFf1h7iFEEN9L3w

###
GET http://localhost:5000/users/1

###
POST http://localhost:5000/users/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoidGVzQGdtYWlsLmNvbSIsImlhdCI6MTc0Nzg0NDcwNiwiZXhwIjoxNzQ3ODQ1NjA2fQ.4Cxn3p-Zqes5y5RY_-waYeObb18SvTGDoL2XBWMtgYs

{
"title": "Gacha Collector YSS",
"category": "Penting",
"text": "Pliss maiiii tanggal 1 jangan lupa gachaaa"
}

###
PATCH http://localhost:5000/users/2
Content-Type: application/json

{
"title": "Bukber 271",
"category": "Moderate",
"text": "Bawa Es Buah"
}

###
DELETE  http://localhost:5000/users/3

### 
GET http://localhost:5000/auth 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoidGVzQGdtYWlsLmNvbSIsImlhdCI6MTc0Nzg0NDQ1MCwiZXhwIjoxNzQ3ODQ1MzUwfQ.kIf4fZgluRJFd51CMkO2DxbyRaU8yFEeMf-jSh0pSws


### 
POST http://localhost:5000/auth 
Content-Type: application/json

{
"username": "test", "email": "tes@gmail.com", "password": "123", "confPassword": "123"
}

### 
POST http://localhost:5000/login 
Content-Type: application/json

{
"email": "tes@gmail.com", "password": "123"
}

### 
GET http://localhost:5000/token

### 
DELETE http://localhost:5000/logout